Made the full website
ArkanKovanAbdullah/HTML-CSS-JavaScript-capstone-project-one pull request #1
Opened 2022-10-21 18:24 UTC by ArkanKovanAbdullah

2022-10-21 23:27 UTC, mckent05 requested changes
Hi @ArkanKovanAbdullah,

# STATUS: CHANGES REQUIRED ♻️ ♻️  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/197304396-bf4d5b52-fbe3-4310-b7dc-5633b1f3a984.gif)

## Highlights
- All linter checks are passing ✔️ 
- Your PR summary and title are descriptive 👏 👏 
- GitHub flow was rightly followed 👍 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-21 23:27 UTC, mckent05 commented on index.html
> +                <img class="width-onehundred-fifty" src="img/airbnb.png" alt="">
- To improve the accessibility of your site, I'd you to add an `alt` text to your images 👍 👍 
- Also, I'd suggest you wrap each image in a `li` tag and wrap your `li` tag in a `ul` tag, this would help improve the HTML structure of your site 👍 👍

2022-10-21 23:27 UTC, mckent05 commented on index.html
> +        </section>
- For a better HTML structure, I advise that you do not wrap your footer in a section. The `footer` tag is enough for this section. I'd suggest you remove the `section` tag 👍 👍 
- In the mobile version of your website, this section is not properly aligned, please ensure that the logo is aligned to the left and the text is aligned to the right.Please try to fix this 🙏 🙏 

# Your project:
<img width="145" alt="arkan mobile footer home" src="https://user-images.githubusercontent.com/73607512/197303328-3b4bfa68-ffd2-45be-9cb8-4cecab9ecdb5.PNG">

2022-10-21 23:27 UTC, mckent05 commented on about.html
> +        </section>
- This section of your page doesn't exactly match the design template. The background color should be black. Please try to fix this 😄. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

# Your project:
<img width="960" alt="arkan about footer" src="https://user-images.githubusercontent.com/73607512/197303781-524c0a68-2875-4f27-a705-e2b1f0247645.PNG">

# Design template:
<img width="553" alt="footer behance about" src="https://user-images.githubusercontent.com/73607512/197303799-68c5fe64-d33b-4068-99ee-457017ee4b99.PNG">

2022-10-21 23:27 UTC, mckent05 commented on about.html
> +        </section>
- This section of your site is not present in the design template, I suggest that fix this 👍 👍

2022-10-21 23:27 UTC, mckent05 commented on README.md
> +To get a local copy up and running follow these simple example steps.
- I appreciate the effort you have put into your video, but please note that according to the project requirements your video presentation shouldn't be more than 5mins. I'd suggest you make another video not longer than 5mins 😄 
- To make your readme look more professional, I'd suggest that you include steps on how to clone your project locally on a computer. Please fix this issue 👍 👍

2022-10-21 23:27 UTC, mckent05 commented on README.md
> +Feel free to check the [issues page](../../issues/).
- According to the project requirements, The README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/). Please include this in your readme

2022-10-22 01:32 UTC, Santiago220991 requested changes
Hi @ArkanKovanAbdullah,
I'm Santiago your reviewer for this PR. :wave: :wave:  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Highlights
:heavy_check_mark: No linter errors.
:heavy_check_mark: Applied most of the changes suggested by the last reviewer.
:heavy_check_mark: Good PR summary.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 01:32 UTC, Santiago220991 commented on index.html
> +            <div><button id="cards-btn" class="padding-30">SEE THE WHOLE PROGRAM</button></div>
Kindly ensure that your project sticks as much as possible to the template provided. I think you did a great job with the desktop version of this section however the mobile version is still showing issues. As [the last code reviewer suggested](https://github.com/ArkanKovanAbdullah/HTML-CSS-JavaScript-capstone-project-one/pull/1#discussion_r1002233119) please pay attention to how is aligned the text in your mobile version. :pray: :pray: 

Your design
![image](https://user-images.githubusercontent.com/98363075/197309951-f680f520-da71-41cf-99cb-d4d56e513691.png)

Template design
![image](https://user-images.githubusercontent.com/98363075/197309882-90e97e73-d9d6-4047-a4bf-aa38d6b788e2.png)

- [OPTIONAL] Kindly add the orange button in the mobile version. :+1: :smiley: :smiley: 
![image](https://user-images.githubusercontent.com/98363075/197310032-e66434a0-4a31-48e6-8ea3-f166a4816883.png)

2022-10-22 01:32 UTC, Santiago220991 commented on index.html
> +            </footer>
As the [last code reviewer suggested](https://github.com/ArkanKovanAbdullah/HTML-CSS-JavaScript-capstone-project-one/pull/1#discussion_r1002248171) kindly fix the footer section in your mobile version. The elements here are should be aligned in a row, the logo is should be aligned to the left and the text should be aligned to the right. Also please pay attention to the background color. :eyes: :eyes: 

Your design
![image](https://user-images.githubusercontent.com/98363075/197310176-24a8a285-2286-4119-a810-3539d09a2747.png)

Template design
![image](https://user-images.githubusercontent.com/98363075/197310288-b1d1e1f0-6a35-4ea2-a791-da25a5f56cae.png)

2022-10-22 02:27 UTC, Ismailco approved these changes
### Hi @ArkanKovanAbdullah, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-10-22 02:27 UTC, Ismailco commented on index.html
> +                <p id="footer-text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptates voluptatem ipsa repellendus maxime quibusdam qui, officia reprehenderit. Esse ea, dicta neque
- [ ] [OPTIONAL] Instead of Lorem ipsum, you can add a short copyright test here so the footer looks like the provided design

2022-10-22 02:45 UTC, merged